const mockDataLocations = {
  apartComplexes: {
    Akademicheskaya: { id: 1, name: "Академический", picked: false },
    Basmannyy: { id: 2, name: "Басманный", picked: false },
    Zamoskvorechye: { id: 3, name: "Замоскворечье", picked: false },
    Izmailovo: { id: 4, name: "Измайлово", picked: false },
    Lyublino: { id: 5, name: "Люблино", picked: false },
  },
  areas: {
    TSAO: { id: 6, name: "ЦАО", picked: false },
    SAO: { id: 7, name: "САО", picked: false },
    SVAO: { id: 8, name: "СВАО", picked: false },
    VAO: { id: 9, name: "ВАО", picked: false },
    YVAO: { id: 10, name: "ЮВАО", picked: false },
    YAO: { id: 11, name: "ЮАО", picked: false },
    YUZAO: { id: 12, name: "ЮЗАО", picked: false },
    ZAO: { id: 13, name: "ЗАО", picked: false },
    SZAO: { id: 14, name: "СЗАО", picked: false },
    ZelAO: { id: 15, name: "ЗелАО", picked: false },
  },
  districts: {
    Tverskoy: { id: 16, name: "Тверской", picked: false },
    Koptevo: { id: 17, name: "Коптево", picked: false },
    Bibirevo: { id: 18, name: "Бибирево", picked: false },
    Novokosino: { id: 19, name: "Новокосино", picked: false },
    Lyublino: { id: 20, name: "Люблино", picked: false },
    Brateyevo: { id: 21, name: "Братеево", picked: false },
    Cheryomushki: { id: 22, name: "Черёмушки", picked: false },
    Kuntsevo: { id: 23, name: "Кунцево", picked: false },
    Mitino: { id: 24, name: "Митино", picked: false },
    Silino: { id: 25, name: "Силино", picked: false },
  },
  stations: {
    Rizhskaya: { id: 26, name: "Рижская", picked: false },
    Timiryazevskaya: { id: 27, name: "Тимирязевская", picked: false },
    Tushinskaya: { id: 28, name: "Тушинская", picked: false },
    Mitino: { id: 29, name: "Митино", picked: false },
    Nizhegorodskaya: { id: 30, name: "Нижегородская", picked: false },
    Novogireyevo: { id: 31, name: "Новогиреево", picked: false },
    Novokosino: { id: 32, name: "Новокосино", picked: false },
    Reutov: { id: 33, name: "Реутов", picked: false },
    Dubrovka: { id: 34, name: "Дубровка", picked: false },
    Pechatniki: { id: 35, name: "Печатники", picked: false },
  },
};
export { mockDataLocations };
